// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_sanity_module_ from "./routes/api/sanity/[module].ts";
import * as $index from "./routes/index.tsx";
import * as $FengbroCrudApp from "./islands/FengbroCrudApp.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/sanity/[module].ts": $api_sanity_module_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/FengbroCrudApp.tsx": $FengbroCrudApp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
